-- Luraph Environment Wrapper B  (Layer 5)
-- chunk_name: "Luraph"
--
-- Identical in purpose to 03_luraph_env_wrapper_a.lua but uses a different
-- internal identifier ("OomXYkQ") generated by a separate Luraph compilation.
-- Sets up the sandboxed fenv for the second Luraph VM (11_luraph_vm_main.lua).

return setfenv(
    function(...)
        return OomXYkQ(...)
    end,
    setmetatable(
        { ["OomXYkQ"] = ... },
        { __index = getfenv((...)) }
    )
)
